inputSpec: https://api.redocly.com/registry/bundle/curvegrid/multibaas/v0/openapi.yaml
outputDir: .
generatorName: python
gitUserId: curvegrid
gitRepoId: multibaas-sdk-python
projectName: multibaas-sdk
# python package name (convention: snake_case).
packageName: multibaas_sdk
packageVersion: 1.0.0
packageUrl: https://github.com/curvegrid/multibaas-sdk-python
licenseInfo: MIT
infoEmail: contact@curvegrid.com
